# Generated by Django 4.1 on 2023-06-19 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.champions')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, '최소 세 글자 이상은 입력해주셔야 합니다.')], verbose_name='댓글 입력')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.champions')),
            ],
        ),
    ]
